version: "3.8"

services:
  api:
    build:
      context: ./server
    restart: always
    env_file:
      - ./server/.env
    container_name: api-zoo
    ports:
      - 3000:3000

  web:
    build:
      context: ./client
    env_file:
      - ./client/.env.local
    restart: always
    container_name: zoo-dashboard
    ports:
      - "3001:3001"
